### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/sapindale#10]
I've created a Docker image for the master branch and deployed it to `docker.c7a.ca/sapindale:20191015`.

What needs to be done to get this deployed somewhere?

**Comment by RussellMcOrmond** [comment]
What should the DNS entry be for this?  

Any other environment variables other than:

```
    environment:
      - "NODE_ENV:production"
```


Are there notes on where to bind mount the ssl keys?
The AMSA config is what I'd be using as a start. Are the volumes the same?

```
    volumes:
      - '/etc/canadiana/pki/__canadiana_ca.key:/amsa/ssl/server.key'
      - '/etc/canadiana/pki/__canadiana_ca.crt:/amsa/ssl/server.crt'
      - '/etc/canadiana/pki/__canadiana_ca.ca-bundle:/amsa/ssl/server.ca-bundle'
```

**Comment by SaschaAdler** [comment]
Environment variables are listed in the Dockerfile (it's already being run under `NODE_ENV=production`, for instance.

SSL volumes can work the same as with amsa. There's an `SSL_DIR` environment variable for finding the files.

**Comment by RussellMcOrmond** [comment]
Note that https://github.com/crkn-rcdr/amsa/issues/4  applies to https://www.sslshopper.com/ssl-checker.html?hostname=auth.canadiana.ca as well.

**Comment by SaschaAdler** [comment]
I've pushed `docker.c7a.ca/sapindale:20190917` which should solve the "undefined everywhere" issue.

**Comment by RussellMcOrmond** [comment]
https://admin.canadiana.ca/ is tested, and the "unknown" seems to be solved.

**Comment by RussellMcOrmond** [comment]
Is there anything more to do on this, or should we close?

**Comment by SaschaAdler** [comment]
I think we're good here.
