### ISSUE TITLE
CouchView: path/get no longer pulled.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#109]
If I go to: https://admin.canadiana.ca/couchview/tdrepo/tdr/replicate?group=1&keytype=json&reduce=true

The controls say Database: canvas , View: Orphan , reduce isn't on, and group level is not set.

**Comment by RussellMcOrmond** [comment]
A a note,  Production (Beth's team) and metadata (Jason's team) use this tool regularly.  An example document from production shows many links to CouchView  (Hammer, Press errors as an example).

https://crkn.sharepoint.com/:w:/s/platform/EWcumgzbmT5EjWBDyMTR0BgBS69Ei5xVSoBMsmzpi4MqtQ?e=aOH4hH

**Comment by RussellMcOrmond** [comment]
In case it is helpful to know, https://admin.canadiana.ca/ is currently running `docker.c7a.ca/sapindale:20210301`

It is possible that the problem has already been fixed in some support library, and all we need to do is deploy an updated version.

`docker build` has a `--no-cache` option which might relate.

I'm also not sure if the image that was build was started by doing a `docker pull node:14-alpine`.  From a systems perspective I prefer to be more explicit so we know what we are getting.  If  `docker pull node:14-alpine` is done today you will get is `node:14.16.0-alpine3.11`

Current tag for https://hub.docker.com/_/node  is `node:15.12.0-alpine3.10`



Please let me know if I can help with building a new image from the `main` branch.

**Comment by RussellMcOrmond** [comment]
https://sapper.svelte.dev/docs#Preloading

This doesn't seem to be working at the moment.  We've switched to using onMount() for CouchView() , but we need to figure out why this isn't working for the future.

**Comment by SaschaAdler** [comment]
I'll close this; we should be writing tools that use views instead of using CouchView from now on.
