### ISSUE TITLE
https://admin.canadiana.ca/packaging :  Remove "Generate SIP (update AIP)" option

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#138]
This is part of the "Adopting new practices with existing tools" part of the Archivematica project.

Archivematica supports metadata updates and new SIPs, and does not allow a SIP to be updated once an AIP is created.  A new SIP requires a new AIP ID.

**Comment by BeS4** [comment]
Yes, please disable the SIP update option. I haven't used it since the P/A split happened since we now have other ways of handling those type of issues now.

**Comment by RussellMcOrmond** [comment]
Complete and deployed.
