### ISSUE TITLE
/couchview/ tool to output IDs.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#15]
Many of the tools currently part of https://github.com/crkn-rcdr/d10n have the purpose of generating a list of IDs that match a specific criteria (Specific element of a grouped view).

* https://workflow.canadiana.ca/demo/filemetaStats.html is similar to https://admin.canadiana.ca/couchview/filemeta/tdr/stats?endkey=&group=3&inclusive=false&reduce=true&startkey= , except for the ability to actually view the files which match a specific key.

**Comment by SaschaAdler** [comment]
This is Archivematica project user story 80.

**Comment by SaschaAdler** [comment]
Solved in above commit.
