### ISSUE TITLE
Drag-and-drop editor

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/sapindale#19]
We're going to need a drag-and-drop editing system in at least two places:

* editing the members of a collection (for now, the issues of a series, but this will be extended to other concepts in the future)
* editing the canvases of a manifest

The interface will need to support re-ordering elements of the list and removing them. A separate but linked interface will probably be used to add elements to the list but we'll need to think things through a bit more on that.

I'll have more ideas to come as the design for the underlying databases for this information is put together.

**Comment by RussellMcOrmond** [comment]
I suspect it is also useful to look at https://github.com/bodleian/iiif-manifest-editor for inspiration, code sharing, etc.

**Comment by SaschaAdler** [comment]
I've merged and closed #20, and after sorting out proxy stuff I'll push an image with the demo.
