### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#25]
We're adopting HAProxy for the entire access platform, and so sapindale will need to work behind it.

**Comment by SaschaAdler** [comment]
See https://github.com/crkn-rcdr/sapindale/commit/d50873f423690d0a119a849c982f556cc2971e90, https://github.com/crkn-rcdr/sapindale/commit/6090fd730edfd4ad36fb14b795cbd1f18545a41d, and the new Docker image I've pushed.

I'll let Russell close this when it's set up in production.

**Comment by RussellMcOrmond** [comment]
This has been tested on Mamirolle, so closing.
