### ISSUE TITLE
Auto-login to upholstery

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#27]
I am wondering if there is a small snipit (include/etc) that can be added to the d10n tools that would periodically connect to sapindale and refresh the browser cookie for upholstery.

I note that production staff is complaining that they have to keep reloading sapindale and re-opening the link to refresh that cookie.

**Comment by RussellMcOrmond** [comment]
I should have checked, as this relates to #6

**Comment by SaschaAdler** [comment]
This issue closes when the legacy d10n tools are no longer in use; we'll still need to figure out #6.
