### ISSUE TITLE
Redirect back to specific page after authentication redirects.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#33]
Currently when you link directly to a page (IE: https://admin.canadiana.ca/couchview/dipstaging/sync/smelts?endkey=%5Bfalse%5D&inclusive=true&reduce=false&startkey=%5Bfalse%5D ) and are not yet authenticated, it will send you back to the home page after authentication.  It would be preferable to end up back where you started.

**Comment by SaschaAdler** [comment]
I think I got this, although there are some problems with IDs that have at one point been URL escaped not being URL escaped.

**Comment by SaschaAdler** [comment]
I'm working around the problem of URL-escaped IDs by having our routes understand when certain IDs (namely, NOIDs) are meant to have a slash in them. This has worked for me anecdotally, and I'm going to close this issue with the aim to re-open if there are further problems.
