### ISSUE TITLE
IIIF text value editor

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/sapindale#52]
Certain text fields (like labels) are internally stored in the IIIF text value format, which looks like:

```
"label": {
  "lang1": ["label1", "label2"],
  "lang2": ["label3", "label4"],
}
```

We'll need a Svelte component for displaying and editing this data structure.

I could see layout of the component working in one of two ways, according to the [figma sketch I sent you](https://www.figma.com/file/L7OvU1k1CGWaSzI3iTDpm3/IIIF-text-value-editor?node-id=0%3A1). Version 1 is simpler but doesn't reflect the underlying data structure as well as version 2. That said, I think version 2 is too fussy and complicated, so let's stick with version 1.

I'll create a user story and Trello card for this, also.

**Comment by SaschaAdler** [comment]
I've removed the drop-down list from the Figma sketch, although I'm still not sure how I feel about it. [There are a lot of languages out there](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), and unless we perform some kind of type-ahead lookup on this large dataset it seems unwieldy to support them all. I don't want to presume that we should only allow, say, the "top ten" that are likely to be found in our data and avoid the rest.

We'll need to brainstorm this a bit further, perhaps. (pinging @RussellMcOrmond as well).

A reminder that the data structure that this component needs to understand is simply:

```
{
  "en": "Label",
  "fr": "French label"
}
```

and not the more complicated scheme used for storage.

We'll also want the text value editor to distinguish between mandatory fields, where at least one key-value pair with a non-empty value exists, and non-mandatory fields, which can have an empty object for a value. (e.g. `collection.label` vs. `collection summary`). The component can be provided a mode toggling this distinction as a property.

**Comment by SaschaAdler** [comment]
This is pretty complicated, the more I think about it.

The text value editor needs to take the following properties:

* data: the underlying data structure being edited. This should be bound to something in the parent component, i.e. `bind:data={collection.label}`
* mandatory: a boolean for whether or not this field is mandatory. For collections, this is true for collection.label, and false for collection.summary
* textarea: a boolean for using a textarea instead of an input for text values

`data` determines how many language-value pairs already show up in the interface. Each pair should have a text input for the language, either a text input or a textarea for the value (toggled by `textarea`, obviously), and, unless it's the only language-value pair left for a `mandatory` field, a clear button that removes the language-value pair.

I've changed my mind on how adding new language-value pairs should work from the call earlier today. The add button should show up at the bottom of the pairs as currently stands. What shouldn't be there by default is the empty language-value pair with the "enter language here" etc. placeholders. Those should only show up when the user tries to add a new pair.

**Comment by DivyaKrishnan26** [comment]
The changes are part of the Collection_editor Branch, 
Although i am having some clarifications for how the mandatory value should be working.
