### ISSUE TITLE
SlugResolver use by "ArchivalManifest.svelte"

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/sapindale#72]
I note in https://github.com/crkn-rcdr/sapindale/commit/3942b4e1cacecdb0969ec1b9dd67c1a029f272e8 that Sascha has ../components/SlugResolver.svelte looking at slugs in collections.

The ArchivalManifest.svelte is using that component to attempt to confirm uniqueness of manifest slugs.

**Comment by SaschaAdler** [comment]
Resolved by #74.
